### login
POST localhost:8084/api/auth/login
Content-Type: application/json

{
  "loginId": "owner",
  "password": "1234"
}

### logout
POST localhost:8084/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwibG9naW4taWQiOiJ1c2VyIiwicm9sZSI6IlJPTEVfTk9STUFMIiwiaWF0IjoxNzg2MzQ3MTI3LCJleHAiOjE3ODYzNTA3Mjd9.RVXuXSQvubveT8cEvVnQ4NVwgu6-o668n1U3_d7GePAu_qmu3dIdzNcNlBRuhYG0tS4DMzmW_tE7h_0tYO4slQ

### refresh
POST localhost:8084/api/auth/refresh
Cookie: refreshToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg2MzQ2NjA1LCJleHAiOjE3ODc1NTYyMDV9.JvYauDRcayiIc8kl1GsHyWcujPRkpJQLwSjPFIuvwPiPEV8esqotY_JT0xMmZKVny--Xrs809u9Vs-08iaf5Ww
Content-Type: application/json